# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fawn', '0004_auto_20170319_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='subject',
            field=models.CharField(max_length=60),
        ),
    ]
