# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fawn', '0005_auto_20170325_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('labw', 'Lab work'), ('controlw', 'Control work'), ('calcw', 'Calculation work'), ('homew', 'Homework'), ('otherw', 'Another type of work')], max_length=100),
        ),
    ]
