# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fawn', '0006_auto_20170325_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fawn.Subject'),
        ),
    ]
