# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fawn', '0006_auto_20170325_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='specialization',
        ),
    ]
