# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fawn', '0007_auto_20170325_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='full_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
