# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fawn', '0009_auto_20170327_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(default='unknown', max_length=30),
        ),
    ]
